name: Release trigger
permissions:
  # use npm trusted publishing via OIDC
  id-token: write
on:
  schedule:
    # daily releases
    - cron: '00 00 * * *'
  push:
    branches:
      - main
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Clone jellyfin-tizen
        uses: actions/checkout@v6
        with:
          repository: 'jellyfin/jellyfin-tizen'
          path: 'jellyfin-tizen'
      - name: Clone jellyfin-web
        uses: actions/checkout@v6
        with:
          repository: 'jellyfin/jellyfin-web'
          path: 'jellyfin-web'
          fetch-tags: true
          fetch-depth: 0
      - name: Use latest jellyfin-web release
        run: |
          cd jellyfin-web
          LATEST_RELEASE=$(git describe --always --tags $(git rev-list --tags) | sed -En '/^v[0-9]+.[0-9]+.[0-9]+$/p' | head -1)
          git checkout $LATEST_RELEASE
          echo "Switching to tag: $LATEST_RELEASE"
          cd ..
      - name: Inherit version from jellyfin-web
        id: version
        run: |
          VERSION=$(jq -r '.version' jellyfin-web/package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: '22'
      - name: Modify jellyfin-tizen/package.json
        id: info
        uses: jaywcjlove/github-action-package@main
        with:
          path: 'jellyfin-tizen/package.json'
          data: |
            {
              "name": "@mibmo/jellyfin-tizen",
              "packageType": "app",
              "appName": "Jellyfin",
              "appPath": "index.html",
              "version": "${{ steps.version.outputs.version }}",
              "repository": {
                "type": "git",
                "url": "git+https://github.com/mibmo/jellyfin-tizen-npm-publish.git"
              },
              "keys": [
                "MediaPlayPause", "MediaPlay", "MediaPause", "MediaStop",
                "MediaTrackPrevious", "MediaTrackNext", "MediaRewind", "MediaFastForward"
              ]
            }
      - name: Set tizen-adapter.js app version
        run: |
          sed -ri 's|version: "DEVELOPMENT"|version: "${{ steps.info.outputs.version }}"|g' tizen-adapter.js
      - name: Include tizen-adapter.js in the app
        run: |
          perl -i -pe 's|\Qwebapis.setAttribute('\''src'\'', '\''\E\$\QWEBAPIS/webapis/webapis.js'\'');\E|webapis.setAttribute('\''src'\'', '\''../tizen-adapter.js'\'');|' jellyfin-tizen/gulpfile.babel.js
      # @TODO: replace this
      - name: Inject skip-intro-button.js in the app
        uses: htsnvhoang/find-replace-multiple@master
        with:
          finds: |
            injectTarget.insertBefore(tizen, apploader);
          replaces: |
            injectTarget.insertBefore(tizen, apploader);

            // inject skip-intro-button.js
            const skipIntro = this.createElement('script');
            skipIntro.setAttribute('src', 'https://cdn.jsdelivr.net/gh/jumoog/intro-skipper/ConfusedPolarBear.Plugin.IntroSkipper/Configuration/inject.js');
            skipIntro.setAttribute('defer', '');
            injectTarget.insertBefore(skipIntro, apploader);
          include: "jellyfin-tizen/gulpfile.babel.js"
          separator: "___"
      - name: Build jellyfin-tizen
        run: |
          # build jellyfin-web
          cd jellyfin-web
          npm ci --no-audit
          USE_SYSTEM_FONTS=1 npm run build:production

          # build jellyfin-tizen
          cd ../jellyfin-tizen
          cp ../tizen-adapter.js .
          rm .gitignore
          JELLYFIN_WEB_DIR=../jellyfin-web/dist npm ci --no-audit
      - name: Publish new @mibmo/jellyfin-tizen package version
        uses: JS-DevTools/npm-publish@v4
        with:
          package: jellyfin-tizen
          access: public
      - name: Release Build Result
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.info.outputs.version }}
          body: "A new version of @mibmo/jellyfin-tizen has been published because of a new release of jellyfin-web."
